image: ruby:2.5.5

variables:
  JEKYLL_ENV: production

before_script:
  - gem update --system
  - gem install bundler
  - bundler update --bundler
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
