language: ruby

rvm: 2.6.6

cache: bundler

before_script:
 - chmod +x ./_scripts/build.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./_scripts/build.sh

before_install:
  - gem update --system
  - gem install bundler
  - bundler update --bundler

install:
  - bundle install

# branch whitelist, only for GitHub Pages
# branches:
#   only:
#   - master
#   - gh-pages     # test the gh-pages branch
#   - /pages-(.*)/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable.
  keep_history: true
  local_dir: _site
  target_branch: master
  on:
    branch: source
